# Generated by Django 3.0.3 on 2020-03-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=50)),
                ('admin_email', models.EmailField(max_length=254)),
                ('admin_password', models.CharField(max_length=20)),
            ],
        ),
    ]
